name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
        touch .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
        echo "CLOUD_NAME=${{ secrets.CLOUD_NAME }}" >> .env
        echo "CLOUD_API_KEY=${{ secrets.CLOUD_API_KEY }}" >> .env
        echo "CLOUD_API_SECRET=${{ secrets.CLOUD_API_SECRET }}" >> .env
        echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
        echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
        echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "ADMIN_MAIL=${{ secrets.ADMIN_MAIL }}" >> .env
        echo "ADMIN_MAIL2=${{ secrets.ADMIN_MAIL2 }}" >> .env
        echo "USER_MAIL=${{ secrets.USER_MAIL }}" >> .env
    - run: cat .env  # Optional: Check if the file contains correct values (For debugging)
